import {
  MCP_TOOL_NAMES,
  normalizeMcpToolName,
  type McpToolName,
} from "./mcpTools";
import { TOOL_NAMES, type ToolName } from "./tools";

export type InternalMutationScope =
  | "none"
  | "routing"
  | "page"
  | "browser"
  | "network";

export interface InternalToolEffect {
  mutationScope: InternalMutationScope;
  mutatesDom: boolean;
  mutatesBrowser: boolean;
}

const READ_EFFECT = {
  mutationScope: "none",
  mutatesDom: false,
  mutatesBrowser: false,
} as const satisfies InternalToolEffect;

const ROUTING_EFFECT = {
  mutationScope: "routing",
  mutatesDom: false,
  mutatesBrowser: false,
} as const satisfies InternalToolEffect;

const PAGE_EFFECT = {
  mutationScope: "page",
  mutatesDom: true,
  mutatesBrowser: true,
} as const satisfies InternalToolEffect;

const BROWSER_EFFECT = {
  mutationScope: "browser",
  mutatesDom: false,
  mutatesBrowser: true,
} as const satisfies InternalToolEffect;

const NETWORK_EFFECT = {
  mutationScope: "network",
  mutatesDom: false,
  mutatesBrowser: true,
} as const satisfies InternalToolEffect;

export const INTERNAL_TOOL_EFFECTS = {
  [TOOL_NAMES.DOM_GET_PAGE_INFO]: READ_EFFECT,
  [TOOL_NAMES.DOM_QUERY]: READ_EFFECT,
  [TOOL_NAMES.DOM_START_ELEMENT_PICK]: PAGE_EFFECT,
  [TOOL_NAMES.DOM_CANCEL_ELEMENT_PICK]: PAGE_EFFECT,
  [TOOL_NAMES.DOM_HIGHLIGHT_ELEMENT]: PAGE_EFFECT,
  [TOOL_NAMES.DOM_CLEAR_HIGHLIGHTS]: PAGE_EFFECT,
  [TOOL_NAMES.DOM_SET_VALUE]: PAGE_EFFECT,
  [TOOL_NAMES.CSS_APPLY_PATCH]: PAGE_EFFECT,
  [TOOL_NAMES.CSS_REMOVE_PATCH]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_TAKE_SCREENSHOT]: READ_EFFECT,
  [TOOL_NAMES.BROWSER_LIST_TABS]: READ_EFFECT,
  [TOOL_NAMES.BROWSER_SET_TARGET_TAB]: ROUTING_EFFECT,
  [TOOL_NAMES.BROWSER_LIST_FRAMES]: READ_EFFECT,
  [TOOL_NAMES.BROWSER_SET_TARGET_FRAME]: ROUTING_EFFECT,
  [TOOL_NAMES.BROWSER_NAVIGATE]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_NAVIGATE_BACK]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_NAVIGATE_FORWARD]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_RELOAD]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_CLOSE]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_RESIZE]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_CLICK]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_HOVER]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_DRAG]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_FILL_FORM]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_TYPE]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_PRESS_KEY]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_SELECT_OPTION]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_MOUSE_MOVE]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_MOUSE_CLICK]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_MOUSE_DOWN]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_MOUSE_UP]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_MOUSE_DRAG]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_MOUSE_WHEEL]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_WAIT_FOR]: READ_EFFECT,
  [TOOL_NAMES.BROWSER_EVALUATE]: PAGE_EFFECT,
  [TOOL_NAMES.BROWSER_HANDLE_DIALOG]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_STORAGE_STATE]: READ_EFFECT,
  [TOOL_NAMES.BROWSER_COOKIE_LIST]: READ_EFFECT,
  [TOOL_NAMES.BROWSER_COOKIE_SET]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_COOKIE_DELETE]: BROWSER_EFFECT,
  [TOOL_NAMES.BROWSER_CONSOLE_MESSAGES]: READ_EFFECT,
  [TOOL_NAMES.DNR_LIST_RULES]: READ_EFFECT,
  [TOOL_NAMES.DNR_UPSERT_HEADER_RULE]: NETWORK_EFFECT,
  [TOOL_NAMES.DNR_REMOVE_RULE]: NETWORK_EFFECT,
  [TOOL_NAMES.MOCK_UPSERT_GET]: NETWORK_EFFECT,
  [TOOL_NAMES.MOCK_REMOVE]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_FETCH_PREPARE]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_PROXY_ENABLE]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_PROXY_DISABLE]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_PROXY_LIST_RULES]: READ_EFFECT,
  [TOOL_NAMES.DEBUGGER_PROXY_UPSERT_RULE]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_PROXY_REMOVE_RULE]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_PROXY_CLEAR_RULES]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_PROXY_LIST_HITS]: READ_EFFECT,
  [TOOL_NAMES.DEBUGGER_NETWORK_START]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_NETWORK_STOP]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_NETWORK_CLEAR]: NETWORK_EFFECT,
  [TOOL_NAMES.DEBUGGER_NETWORK_LIST]: READ_EFFECT,
  [TOOL_NAMES.DEBUGGER_NETWORK_GET]: READ_EFFECT,
  [TOOL_NAMES.DEBUGGER_NETWORK_GET_BODY]: READ_EFFECT,
  [TOOL_NAMES.DEBUGGER_DETACH]: BROWSER_EFFECT,
} as const satisfies Record<ToolName, InternalToolEffect>;

const NO_EXECUTOR = [] as const;

export const MCP_INTERNAL_TOOL_BINDINGS = {
  [MCP_TOOL_NAMES.BROWSER_STATUS]: NO_EXECUTOR,
  [MCP_TOOL_NAMES.BROWSER_OBSERVE]: [TOOL_NAMES.DOM_GET_PAGE_INFO],
  [MCP_TOOL_NAMES.BROWSER_ACT]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_FILL_FORM,
    TOOL_NAMES.BROWSER_CLICK,
    TOOL_NAMES.BROWSER_PRESS_KEY,
    TOOL_NAMES.BROWSER_WAIT_FOR,
  ],
  [MCP_TOOL_NAMES.BROWSER_VERIFY]: [TOOL_NAMES.DOM_GET_PAGE_INFO],
  [MCP_TOOL_NAMES.BROWSER_DEBUG_ACTIVITY]: [
    TOOL_NAMES.DEBUGGER_NETWORK_LIST,
    TOOL_NAMES.BROWSER_CONSOLE_MESSAGES,
  ],
  [MCP_TOOL_NAMES.BROWSER_GET_SELECTED_ELEMENT]: NO_EXECUTOR,
  [MCP_TOOL_NAMES.BROWSER_GET_CONTEXT_DIGEST]: NO_EXECUTOR,
  [MCP_TOOL_NAMES.BROWSER_GET_PLUGIN_CONVERSATION]: NO_EXECUTOR,
  [MCP_TOOL_NAMES.BROWSER_GET_AUDIT_EVENTS]: NO_EXECUTOR,
  [MCP_TOOL_NAMES.BROWSER_GET_LAST_PLUGIN_MESSAGE]: NO_EXECUTOR,
  [MCP_TOOL_NAMES.BROWSER_GET_PAGE_CONTEXT]: [TOOL_NAMES.DOM_GET_PAGE_INFO],
  [MCP_TOOL_NAMES.BROWSER_SNAPSHOT]: [TOOL_NAMES.DOM_GET_PAGE_INFO],
  [MCP_TOOL_NAMES.BROWSER_QUERY_DOM]: [TOOL_NAMES.DOM_QUERY],
  [MCP_TOOL_NAMES.BROWSER_START_ELEMENT_PICKER]: [TOOL_NAMES.DOM_START_ELEMENT_PICK],
  [MCP_TOOL_NAMES.BROWSER_CANCEL_ELEMENT_PICKER]: [TOOL_NAMES.DOM_CANCEL_ELEMENT_PICK],
  [MCP_TOOL_NAMES.BROWSER_HIGHLIGHT_ELEMENT]: [TOOL_NAMES.DOM_HIGHLIGHT_ELEMENT],
  [MCP_TOOL_NAMES.BROWSER_CLEAR_HIGHLIGHTS]: [TOOL_NAMES.DOM_CLEAR_HIGHLIGHTS],
  [MCP_TOOL_NAMES.BROWSER_TAKE_SCREENSHOT]: [TOOL_NAMES.BROWSER_TAKE_SCREENSHOT],
  [MCP_TOOL_NAMES.BROWSER_LIST_TABS]: [TOOL_NAMES.BROWSER_LIST_TABS],
  [MCP_TOOL_NAMES.BROWSER_SET_TARGET_TAB]: [TOOL_NAMES.BROWSER_SET_TARGET_TAB],
  [MCP_TOOL_NAMES.BROWSER_LIST_FRAMES]: [TOOL_NAMES.BROWSER_LIST_FRAMES],
  [MCP_TOOL_NAMES.BROWSER_SET_TARGET_FRAME]: [TOOL_NAMES.BROWSER_SET_TARGET_FRAME],
  [MCP_TOOL_NAMES.BROWSER_NAVIGATE]: [TOOL_NAMES.BROWSER_NAVIGATE],
  [MCP_TOOL_NAMES.BROWSER_NAVIGATE_BACK]: [TOOL_NAMES.BROWSER_NAVIGATE_BACK],
  [MCP_TOOL_NAMES.BROWSER_NAVIGATE_FORWARD]: [TOOL_NAMES.BROWSER_NAVIGATE_FORWARD],
  [MCP_TOOL_NAMES.BROWSER_RELOAD]: [TOOL_NAMES.BROWSER_RELOAD],
  [MCP_TOOL_NAMES.BROWSER_CLOSE]: [TOOL_NAMES.BROWSER_CLOSE],
  [MCP_TOOL_NAMES.BROWSER_RESIZE]: [TOOL_NAMES.BROWSER_RESIZE],
  [MCP_TOOL_NAMES.BROWSER_CLICK]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_CLICK,
  ],
  [MCP_TOOL_NAMES.BROWSER_HOVER]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_HOVER,
  ],
  [MCP_TOOL_NAMES.BROWSER_DRAG]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_DRAG,
  ],
  [MCP_TOOL_NAMES.BROWSER_FILL_FORM]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_FILL_FORM,
  ],
  [MCP_TOOL_NAMES.BROWSER_EXECUTE_ACTION_STAGE]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_FILL_FORM,
    TOOL_NAMES.BROWSER_CLICK,
    TOOL_NAMES.BROWSER_PRESS_KEY,
    TOOL_NAMES.BROWSER_WAIT_FOR,
  ],
  [MCP_TOOL_NAMES.BROWSER_TYPE]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_TYPE,
  ],
  [MCP_TOOL_NAMES.BROWSER_PRESS_KEY]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_PRESS_KEY,
  ],
  [MCP_TOOL_NAMES.BROWSER_SELECT_OPTION]: [
    TOOL_NAMES.DOM_GET_PAGE_INFO,
    TOOL_NAMES.BROWSER_SELECT_OPTION,
  ],
  [MCP_TOOL_NAMES.BROWSER_MOUSE_MOVE_XY]: [TOOL_NAMES.BROWSER_MOUSE_MOVE],
  [MCP_TOOL_NAMES.BROWSER_MOUSE_CLICK_XY]: [TOOL_NAMES.BROWSER_MOUSE_CLICK],
  [MCP_TOOL_NAMES.BROWSER_MOUSE_DOWN]: [TOOL_NAMES.BROWSER_MOUSE_DOWN],
  [MCP_TOOL_NAMES.BROWSER_MOUSE_UP]: [TOOL_NAMES.BROWSER_MOUSE_UP],
  [MCP_TOOL_NAMES.BROWSER_MOUSE_DRAG_XY]: [TOOL_NAMES.BROWSER_MOUSE_DRAG],
  [MCP_TOOL_NAMES.BROWSER_MOUSE_WHEEL_XY]: [TOOL_NAMES.BROWSER_MOUSE_WHEEL],
  [MCP_TOOL_NAMES.BROWSER_WAIT_FOR]: [TOOL_NAMES.BROWSER_WAIT_FOR],
  [MCP_TOOL_NAMES.BROWSER_EVALUATE]: [TOOL_NAMES.BROWSER_EVALUATE],
  [MCP_TOOL_NAMES.BROWSER_HANDLE_DIALOG]: [TOOL_NAMES.BROWSER_HANDLE_DIALOG],
  [MCP_TOOL_NAMES.BROWSER_STORAGE_STATE]: [TOOL_NAMES.BROWSER_STORAGE_STATE],
  [MCP_TOOL_NAMES.BROWSER_COOKIE_LIST]: [TOOL_NAMES.BROWSER_COOKIE_LIST],
  [MCP_TOOL_NAMES.BROWSER_COOKIE_SET]: [TOOL_NAMES.BROWSER_COOKIE_SET],
  [MCP_TOOL_NAMES.BROWSER_COOKIE_DELETE]: [TOOL_NAMES.BROWSER_COOKIE_DELETE],
  [MCP_TOOL_NAMES.BROWSER_CONSOLE_MESSAGES]: [TOOL_NAMES.BROWSER_CONSOLE_MESSAGES],
  [MCP_TOOL_NAMES.BROWSER_SET_DOM_VALUE]: [TOOL_NAMES.DOM_SET_VALUE],
  [MCP_TOOL_NAMES.BROWSER_NETWORK_REQUESTS]: [TOOL_NAMES.DEBUGGER_NETWORK_LIST],
  [MCP_TOOL_NAMES.BROWSER_NETWORK_START_RECORDING]: [TOOL_NAMES.DEBUGGER_NETWORK_START],
  [MCP_TOOL_NAMES.BROWSER_NETWORK_STOP_RECORDING]: [TOOL_NAMES.DEBUGGER_NETWORK_STOP],
  [MCP_TOOL_NAMES.BROWSER_NETWORK_CLEAR]: [TOOL_NAMES.DEBUGGER_NETWORK_CLEAR],
  [MCP_TOOL_NAMES.BROWSER_NETWORK_LIST_REQUESTS]: [TOOL_NAMES.DEBUGGER_NETWORK_LIST],
  [MCP_TOOL_NAMES.BROWSER_NETWORK_GET_REQUEST]: [TOOL_NAMES.DEBUGGER_NETWORK_GET],
  [MCP_TOOL_NAMES.BROWSER_NETWORK_GET_RESPONSE_BODY]: [TOOL_NAMES.DEBUGGER_NETWORK_GET_BODY],
  [MCP_TOOL_NAMES.BROWSER_DEBUGGER_DETACH]: [TOOL_NAMES.DEBUGGER_DETACH],
  [MCP_TOOL_NAMES.BROWSER_PROXY_ENABLE]: [TOOL_NAMES.DEBUGGER_PROXY_ENABLE],
  [MCP_TOOL_NAMES.BROWSER_PROXY_DISABLE]: [TOOL_NAMES.DEBUGGER_PROXY_DISABLE],
  [MCP_TOOL_NAMES.BROWSER_PROXY_LIST_RULES]: [TOOL_NAMES.DEBUGGER_PROXY_LIST_RULES],
  [MCP_TOOL_NAMES.BROWSER_PROXY_UPSERT_RULE]: [TOOL_NAMES.DEBUGGER_PROXY_UPSERT_RULE],
  [MCP_TOOL_NAMES.BROWSER_PROXY_REMOVE_RULE]: [TOOL_NAMES.DEBUGGER_PROXY_REMOVE_RULE],
  [MCP_TOOL_NAMES.BROWSER_PROXY_CLEAR_RULES]: [TOOL_NAMES.DEBUGGER_PROXY_CLEAR_RULES],
  [MCP_TOOL_NAMES.BROWSER_PROXY_LIST_HITS]: [TOOL_NAMES.DEBUGGER_PROXY_LIST_HITS],
  [MCP_TOOL_NAMES.BROWSER_LIST_NETWORK_RULES]: [TOOL_NAMES.DNR_LIST_RULES],
  [MCP_TOOL_NAMES.BROWSER_UPSERT_HEADER_RULE]: [TOOL_NAMES.DNR_UPSERT_HEADER_RULE],
  [MCP_TOOL_NAMES.BROWSER_UPSERT_GET_MOCK]: [TOOL_NAMES.MOCK_UPSERT_GET],
  [MCP_TOOL_NAMES.BROWSER_REMOVE_NETWORK_RULE]: [TOOL_NAMES.DNR_REMOVE_RULE],
  [MCP_TOOL_NAMES.BROWSER_APPLY_CSS_PATCH]: [TOOL_NAMES.CSS_APPLY_PATCH],
  [MCP_TOOL_NAMES.BROWSER_REMOVE_CSS_PATCH]: [TOOL_NAMES.CSS_REMOVE_PATCH],
} as const satisfies Record<McpToolName, readonly ToolName[]>;

export function getInternalToolEffect(toolName: string): InternalToolEffect | null {
  return Object.prototype.hasOwnProperty.call(INTERNAL_TOOL_EFFECTS, toolName)
    ? INTERNAL_TOOL_EFFECTS[toolName as ToolName]
    : null;
}

export function assertMcpExecutorBoundary(
  sourceMcpToolName: string,
  internalToolName: string,
  claimedMutatesBrowser: boolean,
): void {
  const normalizedMcpToolName = normalizeMcpToolName(sourceMcpToolName);
  if (!normalizedMcpToolName) {
    throw new Error(`EXECUTOR_POLICY_VIOLATION: unknown MCP tool ${sourceMcpToolName}.`);
  }

  const allowedExecutors = MCP_INTERNAL_TOOL_BINDINGS[normalizedMcpToolName];
  if (!(allowedExecutors as readonly string[]).includes(internalToolName)) {
    throw new Error(
      `EXECUTOR_POLICY_VIOLATION: ${normalizedMcpToolName} cannot execute ${internalToolName}.`,
    );
  }

  const effect = getInternalToolEffect(internalToolName);
  if (!effect) {
    throw new Error(
      `EXECUTOR_POLICY_VIOLATION: ${internalToolName} has no declared execution effect.`,
    );
  }
  if (!claimedMutatesBrowser && (effect.mutatesBrowser || effect.mutatesDom)) {
    throw new Error(
      `EXECUTOR_POLICY_VIOLATION: read-only ${normalizedMcpToolName} cannot enter ${effect.mutationScope} mutation executor ${internalToolName}.`,
    );
  }
}
